version: '3.3'

services:

  web:
    build: ./app
    ports:
      - 8000:8000
    networks:
      - backend
    command: uvicorn app:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
    env_file:
      - shitfaced.env
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    restart: unless-stopped


  worker:
    build: ./app
    command: celery --app=worker worker --uid=nobody --gid=nogroup --loglevel=warning
    networks:
      - backend
    volumes:
      - ./app:/app
    env_file:
      - shitfaced.env
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - data:/data
    networks:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:4.0.8
    ports:
      - 27017:27017
    networks:
      - backend
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    env_file:
      - shitfaced.env      
    networks:
      - backend
    restart: unless-stopped


  dashboard:
    build: ./app
    command: celery --app=worker flower
    env_file:
      - shitfaced.env
    networks:
      - backend
    depends_on:
      - redis
      - worker
    links:
      - redis
    restart: unless-stopped


networks:
  backend:
    external: true

volumes:
  data:
