version: '3.3'

services:
  web:
    build: ./app
    # ports:
    #   - 8000:8000
    command: uvicorn app:app --host 0.0.0.0 --reload --proxy-headers --forwarded-allow-ips '*'
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    restart: unless-stopped

  worker:
    build: ./app
    command: celery --app=worker worker --uid=nobody --gid=nogroup --loglevel=warning
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped

  dashboard:
    build: ./app
    command: celery --app=worker flower
    # ports:
    #   - 5555:5555
    depends_on:
      - redis
      - worker
    links:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
