version: '3.3'

services:

  web:
    build: ./app
    ports:
      - 8000:8000
    networks:
      - shitfaced
      - backend      
    command: uvicorn app:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
    env_file:
      - shitfaced.env
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

  worker:
    build: ./app
    command: celery --app=worker worker --uid=nobody --gid=nogroup --loglevel=warning
    networks:
      - backend
    volumes:
      - ./app:/app
    env_file:
      - shitfaced.env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7-alpine
    volumes:
      - data:/data
    networks:
      - backend

  mongo:
    image: mongo:4.0.8
    networks:
      - backend

  dashboard:
    build: ./app
    command: celery --app=worker --broker=redis://redis:6379/0 flower
    networks:
      - backend
    depends_on:
      - redis
      - worker
    links:
      - redis


networks:
  shitfaced:
  backend:
    external: true

volumes:
  data:
